ssh fingerprint enhancements

diff --git a/usr/bin/qubes-remote-support-provider b/usr/bin/qubes-remote-support-provider
--- a/usr/bin/qubes-remote-support-provider
+++ b/usr/bin/qubes-remote-support-provider
@@ -4,8 +4,12 @@ set -x
 set -e
 
 preparation() {
-    temp_dir="$(mktemp --directory)"
-    mkdir -p "$temp_dir/keys"
+   if [ ! "$temp_dir" = "" ]; then
+      true "INFO: custom temp_dir"
+      return 0
+   fi
+   temp_dir="$(mktemp --directory)"
+   mkdir -p "$temp_dir/keys"
 }
 
 if test -d ~/.ssh ; then
@@ -48,13 +52,17 @@ ls -la "$temp_dir/qubes-remote-support/keys"
 ## $temp_dir/qubes-remote-support/keys/id_ed25519
 
 ## TODO: sanitize
+hostname="$(cat "$temp_dir/qubes-remote-support/keys/hostname")"
+ssh_algorithm="$(cat "$temp_dir/qubes-remote-support/keys/ssh_algorithm")"
 ssh_fingerprint="$(cat "$temp_dir/qubes-remote-support/keys/ssh_fingerprint")"
+
+ssh_known_keys_line="$hostname $ssh_algorithm $ssh_fingerprint"
 
 mkdir -p ~/.ssh
 cp "$temp_dir/qubes-remote-support/keys/id_ed25519.pub" ~/.ssh/
 cp "$temp_dir/qubes-remote-support/keys/id_ed25519" ~/.ssh/
 ## TODO: test
-echo "$ssh_fingerprint" > ~/.ssh/known_hosts
+echo "$ssh_known_keys_line" > ~/.ssh/known_hosts
 chmod 700 ~/.ssh
 chmod 600 ~/.ssh/*
 
@@ -82,14 +90,24 @@ echo "sudo sourcefile=~/QubesIncoming/${my_vm_name}/1.auth_private anon-server-t
 
 read press_enter_to_continue
 
-## TODO: sanitize
-hostname="$(cat "$temp_dir/qubes-remote-support/keys/hostname")"
-
 echo ""
 echo "INFO: Do you want to SSH to '$hostname'?"
 read press_enter_to_continue
 
 echo ""
-echo "INFO: Trying ssh."
+echo "INFO: Trying SSH..."
 
-ssh "$hostname"
+counter=0
+
+while true ; do
+   counter="$((counter + 1))"
+   if [ "$counter" -ge "500" ]; then
+      echo "ERROR: SSH connection unsuccessful!"
+      exit 1
+   fi
+   if ssh "$hostname" ; then
+      true "INFO: SSH success."
+   else
+      sleep 10
+   fi
+done
