fix, do not restart whonixcheck in redundant cases
comments

diff --git a/usr/lib/qubes-whonix/qubes-whonixsetup b/usr/lib/qubes-whonix/qubes-whonixsetup
--- a/usr/lib/qubes-whonix/qubes-whonixsetup
+++ b/usr/lib/qubes-whonix/qubes-whonixsetup
@@ -46,22 +46,30 @@ elif [ -e /usr/share/anon-gw-base-files/gateway ]; then
         exit 0
     fi
 
-    # If Tor is disabled, start whonix-setup-wizard in quick mode.
+    ## Check if Tor is disabled.
     if grep "^#DisableNetwork 0$" /etc/tor/torrc; then
+        ## Tor is disabled, therefore start whonix-setup-wizard in quick mode.
         kdesudo whonix-setup-wizard quick
-    fi
 
-    ## When whonixcheck is automatically started at boot, while Tor is disabled
-    ## in /etc/tor/torrc, whonixcheck exits silently.
-    ## (whonixcheck does this because it is assumed, that in these cases Whonix
-    ## Setup starts.) (Most likely happens at first boot.)
-    ## If Tor has been enabled, restart whonixcheck daemon so whonixcheck will
-    ## check Tor's bootstrap status among other things.
-    if ! grep "^#DisableNetwork 0$" /etc/tor/torrc ; then
-        ## Check if whonixcheck daemon is even running before attempting to
-        ## restart it. This aids systems where whonixcheck is not installed.
-        if sudo service whonixcheck status ; then
-            sudo service whonixcheck restart || true
+        ## Check if Tor is still disabled.
+        if grep "^#DisableNetwork 0$" /etc/tor/torrc ; then
+           true "Tor is still disabled, therefore take no action."
+        else
+           ## Tor is enabled now, most likely the user enabled it using whonix-setup-wizard.
+
+           ## When whonixcheck is automatically started at boot, while Tor is disabled
+           ## in /etc/tor/torrc, whonixcheck exits silently.
+           ## (whonixcheck does this because it is assumed, that in these cases Whonix
+           ## Setup starts.) (Most likely happens at first boot.)
+           ## If Tor has been enabled, restart whonixcheck daemon so whonixcheck will
+           ## check Tor's bootstrap status among other things.
+
+           ## Check if whonixcheck daemon is even running before attempting to
+           ## restart it. This aids systems where whonixcheck is not installed
+           ## or disabled by the user.
+           if sudo service whonixcheck status ; then
+               sudo service whonixcheck restart || true
+           fi
         fi
     fi
 
